# =============================================================================
# KONFIGURACJA STREAMLIT - PRODUCTION
# =============================================================================

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
# Ciemny motyw (dark mode)
primaryColor = "#667eea"              # Niebieski kolor główny dla przycisków/linków
backgroundColor = "#0e1117"           # Czarne tło główne
secondaryBackgroundColor = "#0e1117"  # To samo tło dla sidebara - ujednolicenie
textColor = "#fafafa"                 # Biały tekst
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false
